package com.yeamgood.godungonline.bean;

public enum MenuCode {
	USER_HOME,
		PURCHASE,
			PURCHASE_REQUEST,
		PRODUCT_MANAGE,
			WEREHOUSE,PRODUCT,BRAND,MEASURE,CATEGORY,
		PERSON_MANAGE,
			SUPPLIER,CUSTOMER,EMPLOYEE,
		SETTING,
			PROFILE,ROLEGODUNG,
	ADMIN_HOME,
		ADMIN_USERS,
		ADMIN_GODUNG,
		ADMIN_ROLES,
		ADMIN_MENU
}
